require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
Layout/LineLength:
  Exclude:
    - "db/migrate/*"
    - "config/initializers/*"
Hc/RailsSpecificActionName:
  Exclude:
    - "app/controllers/concerns/rack_session_fix.rb"
Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"
    - "app/controllers/api/v1/users/registrations_controller.rb"
Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
    - "app/controllers/api/v1/users/registrations_controller.rb"
