version: "3"
services:
  db:
    image: postgres:14.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build: .
    command: bundle exec rails s -p 8001 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "8001:8001"
    depends_on:
      - db
volumes:
  bundle:
  db:
